package com.example.anees.enums

import com.example.anees.utils.Constants

enum class Reciters(
    val reciterName: String,
    val proirty: Boolean = false
) {
    Ibrahim_elAkhdar("إبراهيم الأخضر"),
    Akram_Alalaqmi("أكرم العلاقمي"),
    Maher_Almuaiqly("ماهر المعيقلي"),
    Mohamed_Altblawy("محمد الطبلاوي"),
    Mohamed_Allohaidan("محمد اللحيدان"),
    Mohamed_Ayyoub("محمد أيوب"),
    Mohamed_Saleh_AlemShah("محمد صالح عالم شاه"),
    Mohamed_Jebril("محمد جبريل"),
    Mohamed_Seddik_Almenshawy("محمد صديق المنشاوي"),
    Mohamed_Abdelkarim("محمد عبدالكريم"),
    Mohamed_Abdelhakim_Saeed("محمد عبدالحكيم سعيد العبدالله"),
    Mahmoud_Khalil_Alhusary("محمود خليل الحصري" , proirty = true),
    Idris_Abkar("إدريس أبكر"),
    Mahmoud_Ali_Albanna("محمود علي البنا"),
    Meshary_Alafasy("مشاري العفاسي"),
    Mostafa_Ismail("مصطفى إسماعيل"),
    Mostafa_ElLahouny("مصطفى اللاهوني"),
    Mostafa_Raad_Alazawy("مصطفى رعد العزاوي"),
    Moftah_Alsultany("مفتاح السلطني"),
    ElZein_Mohamed_Ahmed("الزين محمد أحمد"),
    Mohamed_Saeed("محمد سايد"),
    Abdelilah_BenAoun("عبدالإله بن عون"),
    Noreen_Mohamed_Sedeq("نورين محمد صديق"),
    Majed_Alzamil("ماجد الزامل"),
    Yaseen("القارئ ياسين"),
    Maher_Shakhashero("ماهر شخاشيرو"),
    Mahmoud_Elsheemy("محمود الشيمي"),
    Yasser_Salama("ياسر سلامة"),
    Khaled_Almuhanna("خالد المهنا"),
    ElAyyoun_AlKouchy("العيون الكوشي"),
    Adel_Alkalbany("عادل الكلباني"),
    Mousa_Bilal("موسى بلال"),
    Hatem_Farid("حاتم فريد الواعر"),
    Ibrahim_Aljarmi("إبراهيم الجرمي"),
    Mahmoud_Alrefaey("محمود الرفاعي"),
    Tawfeeq_Alsayegh("توفيق الصايغ"),
    Ibrahim_AdDosary("إبراهيم الدوسري"),
    Jamal_Shaker("جمال شاكر عبدالله"),
    Jamaan_Alosaimi("جمعان العصيمي"),
    Yousif_BenNoah("يوسف بن نوح أحمد"),
    Moeed_AlHarthi("معيض الحارثي"),
    Mohamed_Rashad_Alshareef("محمد رشاد الشريف"),
    Khaled_Aljalil("خالد الجليل"),
    Ahmed_Altirabolsy("أحمد الطرابلسي"),
    Abdullah_Alkandari("عبدالله الكندري"),
    Ahmed_Amer("أحمد عامر"),
    Mohamed_Othman_Khan("محمد عثمان خان"),
    Eldokaly_Mohamed("الدوكالي محمد العالم"),
    Khaled_Alqahtani("خالد القحطاني"),
    Elfateh_Mohamed("الفاتح محمد الزبير"),
    Mohamed_Berhij("محمد برهجي"),
    Hassan_AlDaghreery("حسن الدغريري"),
    Mohamed_Alfaqeeh("محمد الفقيه"),
    Junaid_Adam("جنيد آدم عبدالله"),
    Khaled_Alzyady("خالد الزيادي"),
    Tareq_Abdelghany("طارق عبدالغني دعوب"),
    Bandar_Baleela("بندر بليله"),
    Wadie_AlYamani("وديع اليمني"),
    Khaled_Abdelkafy("خالد عبدالكافي"),
    Raad_Mohamed_Alkurdy("رعد محمد الكردي"),
    Abdurrahman_AlOssi("عبدالرحمن العوسي"),
    Mohamed_Khalil("محمد خليل القارئ"),
    Rami_AlDaees("رامي الدعيس"),
    Abdurrahman_AlMajed("عبدالرحمن الماجد"),
    Marwan_Alokry("مروان العكري"),
    Khalifa_AlTunaiji("خليفة الطنيجي"),
    Abdullah_AlMousa("عبدالله الموسى"),
    Abdullah_Alkhalaf("عبدالله الخلف"),
    Mansour_Alsalmi("منصور السالمي"),
    Nasser_Alasfoor("ناصر العصفور"),
    Dawood_Hamza("داود حمزة"),
    Mohamed_AlBokheet("محمد البخيت"),
    Nasser_Almajed("ناصر الماجد"),
    Ahmed_Alswalem("أحمد السويلم"),
    Bader_Alturki("بدر التركي"),
    Ahmed_Khalil_Shahen("أحمد خليل شاهين"),
    Saad_Almogren("سعد المقرن"),
    Ahmed_Elnafis("أحمد النفيس"),
    Ahmed_Deeban("أحمد ديبان"),
    Abdullah_Kamel("عبدالله كامل"),
    Bisha_WaQader_AlKurdi("بيشه وا قادر الكردي"),
    Rachid_Belalia("رشيد بلعالية"),
    Nazeer_AlMaliki("نذير المالكي"),
    Okasha_Kamini("عكاشة كميني"),
    Haitham_AlDokhin("هيثم الدخين"),
    Mohamed_Abo_Senina("محمد أبو سنينة"),
    Mohamed_AlAmeen_Qniwa("محمد الأمين قنيوة"),
    Ahmed_Essa_AlMesrawy("أحمد عيسى المعصراوي"),
    Ibrahim_Koshedan("إبراهيم كشيدان"),
    Hashem_Abo_Dalal("هاشم أبو دلال"),
    Fouad_AlKhamri("فؤاد الخامري"),
    Sayed_Ahmed_Hashimy("سيد أحمد هاشمي"),
    Khaled_Karim_Mohamady("خالد كريم محمدي"),
    MalAllah_Abdulrahman("مال الله عبدالرحمن الجابر"),
    Salman_Alsedeq("سلمان الصديق"),
    Hassan_Saleh("حسن صالح"),
    Abdurrahman_AlShehat("عبدالرحمن الشحات"),
    Saleh_AlQureshi("صالح القريشي"),
    Ibrahim_AlAseeri("إبراهيم العسيري"),
    Saad_AlGhamdi("سعد الغامدي"),
    Saleh_AlShamrani("صالح الشمراني"),
    Faisal_Alhajri("فيصل الهاجري"),
    Anas_AlEmadi("أنس العمادي"),
    Abdulkarim_AlHazmi("عبدالكريم الحازمي"),
    Saud_AlShuraim("سعود الشريم"),
    Sahl_Yaseen("سهل ياسين"),
    Zaki_Dagistani("زكي داغستاني"),
    Sayed_Ramadan("سيد رمضان"),
    Sherzad_Tahir("شيرزاد عبدالرحمن طاهر"),
    Saber_Abdelhakm("صابر عبدالحكم"),
    Sheikh_Shateri("شيخ أبو بكر الشاطري"),
    Saleh_Alsahood("صالح الصاهود"),
    Saleh_Alhabdan("صالح الهبدان"),
    Salah_Albudair("صلاح البدير"),
    Salah_AlHashim("صلاح الهاشم"),
    Salah_Bokhater("صلاح بو خاطر"),
    Adel_Rayan("عادل ريان"),
    Abdulbari_Althubaiti("عبدالبارئ الثبيتي"),
    Ahmed_AlAjmi("أحمد بن علي العجمي"),
    Abdulbari_Mohamed("عبدالباري محمد"),
    Abdulbasit_AbdulSamad("عبدالباسط عبدالصمد"),
    Abdurrahman_Alsodes("عبدالرحمن السديس"),
    Abdulaziz_Alahmad("عبدالعزيز الأحمد"),
    Abdulaziz_Alzahrani("عبدالعزيز الزهراني"),
    Abdullah_Albaijan("عبدالله البعيجان"),
    Abdullah_AlMotrood("عبدالله المطرود"),
    Ahmed_AlHwashi("أحمد الحواشي"),
    Abdullah_Bosfar("عبدالله بصفر"),
    Abdullah_Khiyat("عبدالله خياط"),
    Abdullah_Awad_AlJuhany("عبدالله عواد الجهني"),
    Abdullah_Ghelan("عبدالله غيلان"),
    Abdurashid_Soufi("عبدالرشيد صوفي"),
    Abdulmohsen_AlHarthi("عبدالمحسن الحارثي"),
    Abdulmohsen_AlQasim("عبدالمحسن القاسم"),
    Abdulmohsen_AlObeikan("عبدالمحسن العبيكان"),
    Abdulhadi_Ahmed_Kanakri("عبدالهادي أحمد كناكري"),
    Abdulwadud_Haneef("عبدالودود حنيف"),
    Abdulwali_AlArkani("عبدالولي الأركاني"),
    Ali_AlHudhaifi("علي بن عبدالرحمن الحذيفي"),
    Ali_Jaber("علي جابر"),
    Ali_Haggag_Alsweisy("علي حجاج السويسي"),
    Emad_Zohair_Hafez("عماد زهير حافظ"),
    Abdulaziz_AlTurki("عبدالعزيز التركي"),
    Ahmed_Saber("أحمد صابر"),
    Omar_AlQazabri("عمر القزابري"),
    Fares_Abbad("فارس عباد"),
    Nasser_Alqatami("ناصر القطامي"),
    Nabil_Alrefaei("نبيل الرفاعي"),
    Neama_AlHassan("نعمة الحسان"),
    Hani_AlRefaei("هاني الرفاعي"),
    Ahmed_Nueina("أحمد نعينع"),
    Waleed_Alnaeehi("وليد النائحي"),
    Yasser_AlDosary("ياسر الدوسري"),
    Yasser_AlQurashi("ياسر القرشي"),
    Yasser_AlMazroui("ياسر المزروعي"),
    Yehia_Hawwa("يحيى حوا"),
    Yousif_AlShweay("يوسف الشويعي"),
    Abdullah_Abdal("عبدالله عبدل");

    val imageUrl = "${Constants.RECITERS_IMAGES_URL}$name.jpg"
}
